services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_dev
    networks:
      - default
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  node_modules:

networks:
  default:
    driver: bridge